const SPRITE_BASE = 'https://play.pokemonshowdown.com/sprites';
const POKEAPI_BASE = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon';

/**
 * Showdown sometimes stores species with the form name first
 * (e.g. "Wash Rotom" instead of "Rotom-Wash", "Heat Rotom" instead of "Rotom-Heat").
 * This map corrects reversed display names to their canonical sprite IDs.
 */
const REVERSED_FORM_MAP: Record<string, string> = {
  'wash rotom': 'rotom-wash',
  'heat rotom': 'rotom-heat',
  'frost rotom': 'rotom-frost',
  'fan rotom': 'rotom-fan',
  'mow rotom': 'rotom-mow',
  'charizard y-mega': 'charizard-megay',
  'charizard x-mega': 'charizard-megax',
};

/**
 * Convert a species display name (from team JSONB) to a Showdown sprite ID.
 * Handles reversed Showdown display names (e.g. "Wash Rotom" → "rotom-wash"),
 * Mega suffixes, and regional forms.
 */
export function speciesToSpriteId(species: string): string {
  const lower = species.toLowerCase();
  // Check reversed form map first
  if (REVERSED_FORM_MAP[lower]) return REVERSED_FORM_MAP[lower];
  // Standard: strip non-alphanumeric except hyphens
  return lower.replace(/[^a-z0-9-]/g, '');
}

/**
 * Get the primary sprite URL (Showdown home sprite).
 * The spriteId is already in Showdown's hyphenated format (set during seed).
 * e.g., "raichu-alola", "charizard-megax", "garchomp"
 */
export function getShowdownSprite(spriteId: string): string {
  return `${SPRITE_BASE}/home/${spriteId}.png`;
}

/**
 * Get PokeAPI sprite by dex number (reliable for base forms).
 */
export function getPokeApiSprite(dexNum: number): string {
  return `${POKEAPI_BASE}/other/home/${dexNum}.png`;
}

/**
 * Get the basic PokeAPI sprite (lower quality but highest coverage).
 */
export function getPokeApiBasicSprite(dexNum: number): string {
  return `${POKEAPI_BASE}/${dexNum}.png`;
}

/**
 * Get official artwork from PokeAPI by dex number (475x475 PNG)
 */
export function getOfficialArt(dexNum: number): string {
  return `${POKEAPI_BASE}/other/official-artwork/${dexNum}.png`;
}

/**
 * Get the animated sprite URL for a Pokemon (GIF)
 */
export function getAnimatedSprite(spriteId: string): string {
  return `${SPRITE_BASE}/ani/${spriteId}.gif`;
}

/**
 * Serebii Legends Z-A sprite pack — the source for Pokemon Champions
 * Mega sprites. Used as a fallback for Mega forms that Showdown doesn't
 * host sprites for (all Champions-exclusive Megas like Delphox, Floette,
 * Meganium, Froslass, and ~40 others).
 *
 * Map of spriteId → National Dex number. Generated by verifying each
 * entry against https://www.serebii.net/legendsz-a/pokemon/{dex}-{variant}.png
 * where variant is "m" (default), "mx" (Mega-X), "my" (Mega-Y), or "mz" (Mega-Z).
 *
 * Only megas with a confirmed Serebii sprite are included.
 */
const SEREBII_MEGA_DEX: Record<string, number> = {
  'abomasnow-mega': 460, 'absol-mega': 359, 'absol-megaz': 359,
  'aerodactyl-mega': 142, 'aggron-mega': 306, 'altaria-mega': 334,
  'ampharos-mega': 181, 'audino-mega': 531, 'banette-mega': 354,
  'barbaracle-mega': 689, 'baxcalibur-mega': 998, 'blaziken-mega': 257,
  'camerupt-mega': 323, 'chandelure-mega': 609, 'chesnaught-mega': 652,
  'chimecho-mega': 358, 'crabominable-mega': 740, 'darkrai-mega': 491,
  'delphox-mega': 655, 'diancie-mega': 719, 'dragalge-mega': 691,
  'dragonite-mega': 149, 'drampa-mega': 780, 'eelektross-mega': 604,
  'emboar-mega': 500, 'excadrill-mega': 530, 'falinks-mega': 870,
  'feraligatr-mega': 160, 'floette-mega': 670, 'froslass-mega': 478,
  'gallade-mega': 475, 'garchomp-mega': 445, 'garchomp-megaz': 445,
  'gardevoir-mega': 282, 'glalie-mega': 362, 'glimmora-mega': 970,
  'golisopod-mega': 768, 'golurk-mega': 623, 'greninja-mega': 658,
  'gyarados-mega': 130, 'hawlucha-mega': 701, 'heatran-mega': 485,
  'heracross-mega': 214, 'houndoom-mega': 229, 'kangaskhan-mega': 115,
  'latias-mega': 380, 'latios-mega': 381, 'lopunny-mega': 428,
  'lucario-mega': 448, 'lucario-megaz': 448, 'magearna-mega': 801,
  'magearna-originalmega': 801, 'malamar-mega': 687, 'manectric-mega': 310,
  'mawile-mega': 303, 'medicham-mega': 308, 'meganium-mega': 154,
  'meowstic-fmega': 678, 'meowstic-mmega': 678, 'metagross-mega': 376,
  'mewtwo-megax': 150, 'mewtwo-megay': 150, 'pinsir-mega': 127,
  'pyroar-mega': 668, 'rayquaza-mega': 384, 'sableye-mega': 302,
  'salamence-mega': 373, 'sceptile-mega': 254, 'scizor-mega': 212,
  'scolipede-mega': 545, 'scovillain-mega': 952, 'scrafty-mega': 560,
  'sharpedo-mega': 319, 'skarmory-mega': 227, 'staraptor-mega': 398,
  'starmie-mega': 121, 'steelix-mega': 208, 'swampert-mega': 260,
  'tatsugiri-curlymega': 978, 'tatsugiri-droopymega': 978, 'tatsugiri-stretchymega': 978,
  'tyranitar-mega': 248, 'zeraora-mega': 807, 'zygarde-mega': 718,
};

/**
 * Get the Serebii Legends Z-A sprite URL for a Mega Pokemon, if available.
 * Returns null if the Mega form is not covered (caller should fall through
 * to other sprite sources).
 */
export function getSerebiiMegaSprite(spriteId: string): string | null {
  const dex = SEREBII_MEGA_DEX[spriteId];
  if (!dex) return null;
  let variant = 'm';
  if (spriteId.endsWith('-megax')) variant = 'mx';
  else if (spriteId.endsWith('-megay')) variant = 'my';
  else if (spriteId.endsWith('-megaz')) variant = 'mz';
  return `https://www.serebii.net/legendsz-a/pokemon/${dex}-${variant}.png`;
}

/**
 * Get type icon URL
 */
export function getTypeIcon(type: string): string {
  return `${SPRITE_BASE}/types/${type}.png`;
}

/**
 * Get item sprite URL
 */
export function getItemSpriteUrl(itemId: string): string {
  return `${SPRITE_BASE}/itemicons/${itemId}.png`;
}

/**
 * Type color map for badges/backgrounds
 */
export const TYPE_COLORS: Record<string, string> = {
  Normal: '#A8A77A',
  Fire: '#EE8130',
  Water: '#6390F0',
  Electric: '#F7D02C',
  Grass: '#7AC74C',
  Ice: '#96D9D6',
  Fighting: '#C22E28',
  Poison: '#A33EA1',
  Ground: '#E2BF65',
  Flying: '#A98FF3',
  Psychic: '#F95587',
  Bug: '#A6B91A',
  Rock: '#B6A136',
  Ghost: '#735797',
  Dragon: '#6F35FC',
  Dark: '#705746',
  Steel: '#B7B7CE',
  Fairy: '#D685AD',
};
