-- Fix mega Pokemon abilities from pokemon-showdown/data/pokedex.ts
-- Run: 2026-04-13
-- Many megas had base form abilities instead of their unique mega ability

UPDATE pokemon SET abilities = '{"0": "Thick Fat"}' WHERE id = 'venusaurmega';
UPDATE pokemon SET abilities = '{"0": "Tough Claws"}' WHERE id = 'charizardmegax';
UPDATE pokemon SET abilities = '{"0": "Drought"}' WHERE id = 'charizardmegay';
UPDATE pokemon SET abilities = '{"0": "Mega Launcher"}' WHERE id = 'blastoisemega';
UPDATE pokemon SET abilities = '{"0": "Adaptability"}' WHERE id = 'beedrillmega';
UPDATE pokemon SET abilities = '{"0": "No Guard"}' WHERE id = 'pidgeotmega';
UPDATE pokemon SET abilities = '{"0": "Surge Surfer"}' WHERE id = 'raichumegax';
UPDATE pokemon SET abilities = '{"0": "Surge Surfer"}' WHERE id = 'raichumegay';
UPDATE pokemon SET abilities = '{"0": "Magic Bounce"}' WHERE id = 'clefablemega';
UPDATE pokemon SET abilities = '{"0": "Trace"}' WHERE id = 'alakazammega';
UPDATE pokemon SET abilities = '{"0": "Innards Out"}' WHERE id = 'victreebelmega';
UPDATE pokemon SET abilities = '{"0": "Shell Armor"}' WHERE id = 'slowbromega';
UPDATE pokemon SET abilities = '{"0": "Shadow Tag"}' WHERE id = 'gengarmega';
UPDATE pokemon SET abilities = '{"0": "Parental Bond"}' WHERE id = 'kangaskhanmega';
UPDATE pokemon SET abilities = '{"0": "Huge Power"}' WHERE id = 'starmiemega';
UPDATE pokemon SET abilities = '{"0": "Aerilate"}' WHERE id = 'pinsirmega';
UPDATE pokemon SET abilities = '{"0": "Mold Breaker"}' WHERE id = 'gyaradosmega';
UPDATE pokemon SET abilities = '{"0": "Tough Claws"}' WHERE id = 'aerodactylmega';
UPDATE pokemon SET abilities = '{"0": "Multiscale"}' WHERE id = 'dragonitemega';
UPDATE pokemon SET abilities = '{"0": "Mega Sol"}' WHERE id = 'meganiummega';
UPDATE pokemon SET abilities = '{"0": "Dragonize"}' WHERE id = 'feraligatrmega';
UPDATE pokemon SET abilities = '{"0": "Mold Breaker"}' WHERE id = 'ampharosmega';
UPDATE pokemon SET abilities = '{"0": "Sand Force"}' WHERE id = 'steelixmega';
UPDATE pokemon SET abilities = '{"0": "Technician"}' WHERE id = 'scizormega';
UPDATE pokemon SET abilities = '{"0": "Skill Link"}' WHERE id = 'heracrossmega';
UPDATE pokemon SET abilities = '{"0": "Stalwart"}' WHERE id = 'skarmorymega';
UPDATE pokemon SET abilities = '{"0": "Solar Power"}' WHERE id = 'houndoommega';
UPDATE pokemon SET abilities = '{"0": "Sand Stream"}' WHERE id = 'tyranitarmega';
UPDATE pokemon SET abilities = '{"0": "Lightning Rod"}' WHERE id = 'sceptilemega';
UPDATE pokemon SET abilities = '{"0": "Speed Boost"}' WHERE id = 'blazikenmega';
UPDATE pokemon SET abilities = '{"0": "Swift Swim"}' WHERE id = 'swampertmega';
UPDATE pokemon SET abilities = '{"0": "Pixilate"}' WHERE id = 'gardevoirmega';
UPDATE pokemon SET abilities = '{"0": "Magic Bounce"}' WHERE id = 'sableyemega';
UPDATE pokemon SET abilities = '{"0": "Huge Power"}' WHERE id = 'mawilemega';
UPDATE pokemon SET abilities = '{"0": "Filter"}' WHERE id = 'aggronmega';
UPDATE pokemon SET abilities = '{"0": "Pure Power"}' WHERE id = 'medichammega';
UPDATE pokemon SET abilities = '{"0": "Intimidate"}' WHERE id = 'manectricmega';
UPDATE pokemon SET abilities = '{"0": "Strong Jaw"}' WHERE id = 'sharpedomega';
UPDATE pokemon SET abilities = '{"0": "Sheer Force"}' WHERE id = 'cameruptmega';
UPDATE pokemon SET abilities = '{"0": "Pixilate"}' WHERE id = 'altariamega';
UPDATE pokemon SET abilities = '{"0": "Prankster"}' WHERE id = 'banettemega';
UPDATE pokemon SET abilities = '{"0": "Levitate"}' WHERE id = 'chimechomega';
UPDATE pokemon SET abilities = '{"0": "Magic Bounce"}' WHERE id = 'absolmega';
UPDATE pokemon SET abilities = '{"0": "Refrigerate"}' WHERE id = 'glaliemega';
UPDATE pokemon SET abilities = '{"0": "Aerilate"}' WHERE id = 'salamencemega';
UPDATE pokemon SET abilities = '{"0": "Tough Claws"}' WHERE id = 'metagrossmega';
UPDATE pokemon SET abilities = '{"0": "Levitate"}' WHERE id = 'latiasmega';
UPDATE pokemon SET abilities = '{"0": "Levitate"}' WHERE id = 'latiosmega';
UPDATE pokemon SET abilities = '{"0": "Delta Stream"}' WHERE id = 'rayquazamega';
UPDATE pokemon SET abilities = '{"0": "Intimidate"}' WHERE id = 'staraptormega';
UPDATE pokemon SET abilities = '{"0": "Scrappy"}' WHERE id = 'lopunnymega';
UPDATE pokemon SET abilities = '{"0": "Sand Force"}' WHERE id = 'garchompmega';
UPDATE pokemon SET abilities = '{"0": "Adaptability"}' WHERE id = 'lucariomega';
UPDATE pokemon SET abilities = '{"0": "Snow Warning"}' WHERE id = 'abomasnowmega';
UPDATE pokemon SET abilities = '{"0": "Inner Focus"}' WHERE id = 'gallademega';
UPDATE pokemon SET abilities = '{"0": "Snow Warning"}' WHERE id = 'froslassmega';
UPDATE pokemon SET abilities = '{"0": "Flash Fire"}' WHERE id = 'heatranmega';
UPDATE pokemon SET abilities = '{"0": "Bad Dreams"}' WHERE id = 'darkraimega';
UPDATE pokemon SET abilities = '{"0": "Mold Breaker"}' WHERE id = 'emboarmega';
UPDATE pokemon SET abilities = '{"0": "Piercing Drill"}' WHERE id = 'excadrillmega';
UPDATE pokemon SET abilities = '{"0": "Healer"}' WHERE id = 'audinomega';
UPDATE pokemon SET abilities = '{"0": "Poison Point"}' WHERE id = 'scolipedemega';
UPDATE pokemon SET abilities = '{"0": "Shed Skin"}' WHERE id = 'scraftymega';
UPDATE pokemon SET abilities = '{"0": "Levitate"}' WHERE id = 'eelektrossmega';
UPDATE pokemon SET abilities = '{"0": "Infiltrator"}' WHERE id = 'chandeluremega';
UPDATE pokemon SET abilities = '{"0": "Unseen Fist"}' WHERE id = 'golurkmega';
UPDATE pokemon SET abilities = '{"0": "Bulletproof"}' WHERE id = 'chesnaughtmega';
UPDATE pokemon SET abilities = '{"0": "Levitate"}' WHERE id = 'delphoxmega';
UPDATE pokemon SET abilities = '{"0": "Protean"}' WHERE id = 'greninjamega';
UPDATE pokemon SET abilities = '{"0": "Rivalry"}' WHERE id = 'pyroarmega';
UPDATE pokemon SET abilities = '{"0": "Fairy Aura"}' WHERE id = 'floettemega';
UPDATE pokemon SET abilities = '{"0": "Contrary"}' WHERE id = 'malamarmega';
UPDATE pokemon SET abilities = '{"0": "Tough Claws"}' WHERE id = 'barbaraclemega';
UPDATE pokemon SET abilities = '{"0": "Poison Point"}' WHERE id = 'dragalgemega';
UPDATE pokemon SET abilities = '{"0": "No Guard"}' WHERE id = 'hawluchamega';
UPDATE pokemon SET abilities = '{"0": "Magic Bounce"}' WHERE id = 'dianciemega';
UPDATE pokemon SET abilities = '{"0": "Iron Fist"}' WHERE id = 'crabominablemega';
UPDATE pokemon SET abilities = '{"0": "Emergency Exit"}' WHERE id = 'golisopodmega';
UPDATE pokemon SET abilities = '{"0": "Berserk"}' WHERE id = 'drampamega';
UPDATE pokemon SET abilities = '{"0": "Soul-Heart"}' WHERE id = 'magearnamega';
UPDATE pokemon SET abilities = '{"0": "Volt Absorb"}' WHERE id = 'zeraoramega';
UPDATE pokemon SET abilities = '{"0": "Battle Armor"}' WHERE id = 'falinksmega';
UPDATE pokemon SET abilities = '{"0": "Spicy Spray"}' WHERE id = 'scovillainmega';
UPDATE pokemon SET abilities = '{"0": "Adaptability"}' WHERE id = 'glimmoramega';
UPDATE pokemon SET abilities = '{"0": "Commander"}' WHERE id = 'tatsugiricurlymega';
UPDATE pokemon SET abilities = '{"0": "Commander"}' WHERE id = 'tatsugiridroopymega';
UPDATE pokemon SET abilities = '{"0": "Commander"}' WHERE id = 'tatsugiristretchymega';
UPDATE pokemon SET abilities = '{"0": "Thermal Exchange"}' WHERE id = 'baxcaliburmega';
